README.md
            - ชื่อ: https://github.com
  การใช้งาน: actions/upload-artifact@v4.3.6
  กับ:
    # ชื่อสิ่งประดิษฐ์
    ชื่อ: # ตัวเลือก ค่าเริ่มต้นคือสิ่งประดิษฐ์
    # ไฟล์ ไดเรกทอรี หรือรูปแบบไวด์การ์ดที่อธิบายถึงสิ่งที่จะอัปโหลด
    เส้นทาง:
    # พฤติกรรมที่ต้องการหากไม่พบไฟล์จากเส้นทางที่ให้มา
ตัวเลือกที่มี:
  warn: แสดงคำเตือนแต่ไม่ล้มเหลวในการดำเนินการ
  ข้อผิดพลาด: การดำเนินการล้มเหลวโดยมีข้อความแสดงข้อผิดพลาด
  ไม่สนใจ: ไม่แสดงคำเตือนหรือข้อผิดพลาดใด ๆ การกระทำจะไม่ล้มเหลว

    if-no-files-found: # ตัวเลือก ค่าเริ่มต้นคือ warn
    # ระยะเวลาที่สิ่งประดิษฐ์จะหมดอายุเป็นวัน 0 หมายถึงใช้การคงไว้เป็นค่าเริ่มต้น
ขั้นต่ำ 1 วัน สูงสุด 90 วัน เว้นแต่จะเปลี่ยนแปลงจากหน้าการตั้งค่าที่เก็บข้อมูล

    วันเก็บรักษา: # ตัวเลือก
    # ระดับการบีบอัดสำหรับ Zlib ที่จะนำไปใช้กับไฟล์เก็บถาวรอาร์ทิแฟกต์ ค่าสามารถอยู่ระหว่าง 0 ถึง 9: - 0: ไม่มีการบีบอัด - 1: ความเร็วที่ดีที่สุด - 6: การบีบอัดเริ่มต้น (เช่นเดียวกับ GNU Gzip) - 9: การบีบอัดที่ดีที่สุด ระดับที่สูงกว่าจะส่งผลให้การบีบอัดดีขึ้น แต่จะใช้เวลาในการดำเนินการนานกว่า สำหรับไฟล์ขนาดใหญ่ที่ไม่สามารถบีบอัดได้ง่าย แนะนำให้ใช้ค่า 0 เพื่อการอัปโหลดที่เร็วขึ้นอย่างเห็นได้ชัด

    ระดับการบีบอัด: # ตัวเลือก ค่าเริ่มต้นคือ 6
    # หากเป็นจริง สิ่งประดิษฐ์ที่มีชื่อตรงกันจะถูกลบออกก่อนที่จะอัปโหลดสิ่งประดิษฐ์ใหม่ หากเป็นเท็จ การดำเนินการจะล้มเหลวหากมีสิ่งประดิษฐ์สำหรับชื่อที่กำหนดไว้แล้ว จะไม่ล้มเหลวหากไม่มีสิ่งประดิษฐ์ดังกล่าว

    เขียนทับ: # ตัวเลือก ค่าเริ่มต้นคือเท็จ
                 - ชื่อ: ตั้งค่าสภาพแวดล้อม Node.js
  ใช้: actions/setup-node@v4.0.3
  กับ:
    # ตั้งค่า always-auth ใน npmrc
    always-auth: # ตัวเลือก ค่าเริ่มต้นคือ false
    # เวอร์ชัน ข้อมูลจำเพาะของเวอร์ชันที่จะใช้ ตัวอย่าง: 12.x, 10.15.1, >=10.15.0
    เวอร์ชันโหนด: # ตัวเลือก
    # ไฟล์ที่ประกอบด้วยข้อมูลจำเพาะของเวอร์ชันที่จะใช้ ตัวอย่าง: package.json, .nvmrc, .node-version, .tool-versions
    ไฟล์ node-version: # ตัวเลือก
    # สถาปัตยกรรมเป้าหมายสำหรับ Node ที่จะใช้ ตัวอย่าง: x86, x64 จะใช้สถาปัตยกรรมระบบตามค่าเริ่มต้น
    สถาปัตยกรรม: # ตัวเลือก
    # ตั้งค่าตัวเลือกนี้หากคุณต้องการให้การดำเนินการตรวจสอบเวอร์ชันล่าสุดที่มีอยู่ซึ่งตรงตามข้อกำหนดเวอร์ชัน
    ตรวจสอบล่าสุด: # ตัวเลือก
    # รีจิสทรีเสริมสำหรับการตั้งค่าการรับรองความถูกต้อง จะตั้งค่ารีจิสทรีในไฟล์ .npmrc และ .yarnrc ในระดับโครงการ และตั้งค่าการรับรองความถูกต้องเพื่ออ่านข้อมูลจาก env.NODE_AUTH_TOKEN
    registry-url: # ตัวเลือก
    # ขอบเขตเสริมสำหรับการรับรองความถูกต้องกับรีจิสทรีที่มีขอบเขต จะย้อนกลับไปยังเจ้าของที่เก็บข้อมูลเมื่อใช้รีจิสทรี GitHub Packages (https://npm.pkg.github.com/)
    ขอบเขต: # ตัวเลือก
    # ใช้ในการดึงข้อมูลการแจกจ่ายโหนดจากเวอร์ชันโหนด เนื่องจากมีค่าเริ่มต้น จึงมักไม่ได้ระบุโดยผู้ใช้ เมื่อเรียกใช้การดำเนินการนี้บน github.com ค่าเริ่มต้นก็เพียงพอแล้ว เมื่อเรียกใช้บน GHES คุณสามารถส่งโทเค็นการเข้าถึงส่วนบุคคลสำหรับ github.com ได้หากคุณประสบปัญหาการจำกัดอัตรา
    โทเค็น: # ตัวเลือก ค่าเริ่มต้นคือ ${{ github.server_url == 'https://github.com' && github.token || '' }}
    # ใช้เพื่อระบุตัวจัดการแพ็กเกจสำหรับการแคชในไดเร็กทอรีเริ่มต้น ค่าที่รองรับ: npm, yarn, pnpm
    แคช: # ตัวเลือก
    # ใช้เพื่อระบุเส้นทางไปยังไฟล์การอ้างอิง: package-lock.json, yarn.lock เป็นต้น รองรับไวด์การ์ดหรือรายชื่อไฟล์เพื่อแคชการอ้างอิงหลายรายการ
    เส้นทางการพึ่งพาแคช: # ตัวเลือก
               
